### ISSUE TITLE
trouble setting up card(s)

### ISSUE THREAD

**Issue by aaronsb** [phrz/lg-washer-dryer-card#1]
I keep getting complaints about "bad mapping of an entity" on the first line of either the washer or dryer card.

The instructions tell me to rename sensor.washer (and some other sensors) to corresponding entity IDs or run state sensors. Can you provide some examples?

**Comment by phrz** [comment]
Hi, I responded to your Reddit post which was hopefully some help. If not, try listing the entity IDs belonging to the LG ThinQ integration. Did you edit configuration.yaml and reboot Home Assistant for the changes to take effect? The template sensors in that configuration are necessary for these cards.

**Comment by phrz** [comment]
I updated my README to be more precise about changing entity names in both the configuration file as well as the code for the cards. I also was more explicit that you need to reboot HA for changes to configuration.yaml to be effective. Let me know if either of these was the cause.

**Comment by aaronsb** [comment]
I did restart homeassistant and there were not a lot of changes. I'm sorry I might have construed two problems together into one. (I'm having a hunch that the lovelace card config is related to not seeing the entities)

Here's a screenshot of what happens when I just paste the washer-card.yaml into a manual card, you can see there's an issue with element mapping.

I've verified that the paths referred for the images (from /www/...) are accessible from the homeassistant url, for example http://hass.domain.local:8123/lcoal/lg-icons/dry.png is visible.

![image](https://user-images.githubusercontent.com/2738471/112726241-59803d00-8eea-11eb-8899-b80d9b24b522.png)

**Comment by aaronsb** [comment]
'no card type found' is the previous error since a blank manual card always starts with type: ''

**Comment by aaronsb** [comment]
additionally, this is what the washer entities look like, so I guess I'm still ambiguous on what needs to be renamed. I _think_ that it's already correct, based on your instructions.

![image](https://user-images.githubusercontent.com/2738471/112726304-a95f0400-8eea-11eb-9ff5-ed524ad56538.png)

**Comment by phrz** [comment]
@aaronsb it doesn't look like anything needs renaming, you have the same naming scheme as me. 

Someone alerted me to a typo in my card YAML that may have been the cause of your issue. I've resolved it in the latest commit, but you can just stick a hyphen at the beginning of line 3. If that was the cause of your issue, I'm very sorry for the sloppy typing.

**Comment by aaronsb** [comment]
Yes it must have been the typo!

Troubleshooting YAML syntax has always been a weak spot for me. I suspected maybe there was an incompatibility or typo, and I thought this would be the best place to discuss!

Thank you for updating the cards it worked first try after the edit.

![image](https://user-images.githubusercontent.com/2738471/112733825-29e42b80-8f10-11eb-9130-aadc61f0afa9.png)
