### ISSUE TITLE
Feature request: Child lock icons/status

### ISSUE THREAD

**Issue by Hootie81** [phrz/lg-washer-dryer-card#12]
Thanks for a beautiful card, it looks great on the kitchen display. 

one thing I would love to see is the child-lock status at a glance when my 2yr old disappears for more than 10seconds!

Following the way you created the other template sensors I created this
```
washer_child_lock:
  friendly_name: "Washer Child Lock"
  value_template: "{{ state_attr('sensor.washer','child_lock') }}"
```

and can see how to update the card to display the icons, that's pretty simple

Are you able to create some icons in the same style and colors of the others? I can't seem to figure out transparency

**Comment by phrz** [comment]
Already implemented as `washer_door_lock`.

**Comment by phrz** [comment]
And thank you!! Sorry I didn't check these issues in forever.
