### ISSUE TITLE
Multiple images not showing u p 

### ISSUE THREAD

**Issue by drezin2112** [phrz/lg-washer-dryer-card#14]
Have I missed an image?

![image](https://user-images.githubusercontent.com/89281275/160266367-773e6d27-d8b6-4f33-9fcb-7aeffa1a62e6.png)

![image](https://user-images.githubusercontent.com/89281275/160266385-5230cd72-4e70-49dc-aa8c-c3fd92a61068.png)

![image](https://user-images.githubusercontent.com/89281275/160266390-d50287ee-8401-497f-971d-949fe637edea.png)

Please let me know what I am doing wrong.

**Comment by freggel2** [comment]
Yep, I've had the same issue.
Make a new folder in your www folder named: lg-icons

In that new folder place all of your lg icons. Refresh browser and the icons are shown up.

**Comment by phrz** [comment]
Hi, @drezin2112 , are you still experiencing this issue? As freggel noted, it's important to keep the www files in the same structure as they appear in this repo. If you still experience the issue, it usually goes away after a cache reset in your browser.
