### ISSUE TITLE
Wash status is not displayed 

### ISSUE THREAD

**Issue by doemu0992** [phrz/lg-washer-dryer-card#15]
Hello all,

Unfortunately, the washing status is not displayed on the Virtual Dislpay. 

<img width="1679" alt="lg" src="https://user-images.githubusercontent.com/104934446/175328907-bcd70ad1-962a-45a5-9af8-05e8b784e584.png">

Here is my code: 

#LG washing machine YAML:

sensor:
- platform: template
  sensors:
     washer_door_lock:
       friendly_name: "Washer Door Lock"
       value_template: "{{ state_attr('sensor.washer','door_lock') }}"

     washer_time_display:
       friendly_name: "Washer Time Display"
       value_template: >
         {% if is_state('sensor.washer_run_state', '-') %}
         {% elif is_state('sensor.washer_run_state', 'Standby') %}
           -:--
         {% else %}
           {{ state_attr('sensor.washing_machine', 'remain_time') }}
         {% endif %}
 
     blank:
       friendly_name: "Blank Sensor"
       value_template: ""

Card Code: 
      
   type: picture-elements
elements:
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/dry.png
    state_image:
      Drying: /local/lg-icons/dry-on.png
    style:
      top: 73%
      left: 59
      width: 10%
      image-rendering: crisp
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/cool.png
    state_image:
      Cooling: /local/lg-icons/cool-on.png
    style:
      top: 73%
      left: 67
      width: 10%
      image-rendering: crisp
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/sensing.png
    state_image:
      Detecting: /local/lg-icons/sensing-on.png
    style:
      top: 33%
      left: 33%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/wash.png
    state_image:
      Washing: /local/lg-icons/wash-on.png
    style:
      top: 33%
      left: 51
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/rinse.png
    state_image:
      Rinsing: /local/lg-icons/rinse-on.png
    style:
      top: 33%
      left: 69
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washing_machine_run_state
    image: /local/lg-icons/spin.png
    state_image:
      Spinning: /local/lg-icons/spin-on.png
    style:
      top: 33%
      left: 87%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washer
    image: /local/lg-icons/wifi.png
    state_image:
      'on': /local/lg-icons/wifi-on.png
    style:
      top: 73%
      left: 32
      width: 10%
      image-rendering: crisp
  - type: image
    entity: sensor.washer_door_lock
    image: /local/lg-icons/lock.png
    state_image:
      'on': /local/lg-icons/lock-on.png
    style:
      'top': 73%
      left: 45
      width: 10%
      image-rendering: crisp
  - type: state-label
    entity: sensor.blank
    prefix: '18:88'
    style:
      colour: '#555'
      font-family: segment7
      font-size: 50px
      left: 95%
      top: 74%
      transform: translate(-100%,-50%)
  - type: state-label
    entity: sensor.washer_time_display
    style:
      colour: '#8df427'
      font-family: segment7
      font-size: 50px
      left: 95%
      top: 74%
      transform: translate(-100%,-50%)
image: /local/hass-combo-card-bg.png

**Comment by liuhuaipu** [comment]
I also encountered the same problem, did you solve it?

**Comment by liuhuaipu** [comment]
I don't know where to start.

**Comment by doemu0992** [comment]
> I don't know where to start

It's the same for me, I've tried almost everything. Unfortunately without success

**Comment by raliseda** [comment]
did you check that the name that is displayed under the sensors integration match exactly with the card? washing, rinsing etc. I had the same problem and the name was different. I change them and it worked well! hope that helps.

**Comment by liuhuaipu** [comment]
![微信截图_20220705104155](https://user-images.githubusercontent.com/72367276/177239139-ba49b428-8a5c-4f61-a240-3463500c70b0.png)
![微信截图_20220705104239](https://user-images.githubusercontent.com/72367276/177239145-0671f440-9bf8-4055-b258-5bba9b5e6257.png)

**Comment by liuhuaipu** [comment]
> 您是否检查过传感器集成下显示的名称与卡完全匹配？洗涤，漂洗等。我有同样的问题，名称不同。我改变了它们，效果很好！希望有帮助。
Can you share your configuration code as a reference? Because I can't find out where my wrong setting is.

**Comment by liuhuaipu** [comment]
Can you share your card configuration code as a reference? Because I can't find out where my wrong setting is.

**Comment by raliseda** [comment]
here it is, since my application is in spanish, I had too match the name sensors (runstate name) with the card: I use bold text to identify where you need to match the names with the names that add up in your integration.

type: vertical-stack
cards:
  - type: picture-elements
    elements:
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/dry.png
        state_image:
          **_Secando_**: /local/lg-icons/dry-on.png
        style:
          top: 73%
          left: 59%
          width: 10%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/cool.png
        state_image:
          **_Enfriando_**: /local/lg-icons/cool-on.png
        style:
          top: 73%
          left: 67%
          width: 10%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/sensing.png
        state_image:
          **_Detectando_**: /local/lg-icons/sensing-on.png
        style:
          top: 33%
          left: 33%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/wash.png
        state_image:
          **_Lavando_**: /local/lg-icons/wash-on.png
        style:
          top: 33%
          left: 51%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/rinse.png
        state_image:
          **_Enjuagando_**: /local/lg-icons/rinse-on.png
        style:
          top: 33%
          left: 69%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora_run_state
        image: /local/lg-icons/spin.png
        state_image:
          **_Centrifugando_**: /local/lg-icons/spin-on.png
        style:
          top: 33%
          left: 87%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.lavadora
        image: /local/lg-icons/wifi.png
        state_image:
          'on': /local/lg-icons/wifi-on.png
        style:
          top: 73%
          left: 32%
          width: 10%
          image-rendering: crisp
      - type: image
        entity: binary_sensor.lavadora_door_close
        image: /local/lg-icons/lock.png
        state_image:
          'on': /local/lg-icons/lock-on.png
        style:
          top: 73%
          left: 45%
          width: 10%
          image-rendering: crisp
      - type: state-label
        entity: sensor.blank
        prefix: '18:88'
        style:
          color: '#555'
          font-family: segment7
          font-size: 50px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
      - type: state-label
        entity: sensor.lavadora_time_display
        style:
          color: '#8df427'
          font-family: segment7
          font-size: 50px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
    image: /local/hass-combo-card-bg.png
  - type: conditional
    conditions:
      - entity: sensor.lavadora_run_state
        state_not: '-'
      - entity: sensor.lavadora_run_state
        state_not: Standby
    card:
      type: entities
      entities:
        - entity: sensor.lavadora
          type: attribute
          attribute: water_temp
          name: Water Temperature
          icon: mdi:coolant-temperature
        - entity: sensor.lavadora
          type: attribute
          attribute: spin_speed
          name: Spin Speed
          icon: mdi:rotate-right
        - entity: sensor.lavadora_dry_level
          type: attribute
          attribute: dry_level
          name: Dry Level
          icon: mdi:air-filter
        - entity: sensor.lavadora
          type: attribute
          attribute: run_state
          name: Current State
          icon: mdi:archive
        - entity: sensor.lavadora
          type: attribute
          attribute: tubclean_count
          name: Washes Since Tub Clean
          icon: mdi:creation
      state_color: false

**Comment by doemu0992** [comment]
Hello together,

Will try this with the status of the process tonight.

**Comment by phrz** [comment]
Hi y'all, sorry for the delayed response. Just to confirm what has been suggested, this card is programmed for English language sensor values. If your installation is in another language, you need to change it to match the values as they appear in your set language. That is, wherever you see a state name in the YAML, such as:
```yaml
state_image:
  Detecting: /local/lg-icons/sensing-on.png
```
You would need to change it to (for example, in Spanish)
```yaml
state_image:
  Detectando: /local/lg-icons/sensing-on.png
```
And so on for your localization settings. This is not an issue with this project, but a limitation of the LG integration, which uses localized state names that cannot be automatically adapted to when the language changes. I believe the language they appear in actually depends upon the language of your LG account rather than your Home Assistant installation.

I'm going to close this for now, but please feel free to ask for more clarification if you need it.
