### ISSUE TITLE
Card Backgrounds for WM4000HWA and DLEX4000W

### ISSUE THREAD

**Issue by ChrisRomp** [phrz/lg-washer-dryer-card#17]
Not sure the best spot for this, but I've made some quick-and-dirty card backgrounds for the `WM4000HWA` washer and `DLEX4000W` dryer:

![hass-washer-wm4000hwa-card-bg](https://user-images.githubusercontent.com/1683889/194162547-4179dfd4-9dee-4848-9493-f06fc2c85fa9.png)

![hass-dryer-dlex4000w-card-bg](https://user-images.githubusercontent.com/1683889/194162567-9116e331-7153-415b-8911-49c61ab43ddf.png)

**Comment by NightMean** [comment]
also mentioned in #21

**Comment by phrz** [comment]
Merged #21
