### ISSUE TITLE
README.md image links are b0rked

### ISSUE THREAD

**Issue by wenestvedt** [phrz/lg-washer-dryer-card#18]
There are two embedded images at the top of the README.md which don't load.

Currently they display this text:
`![IMG_1843 2](https://user-images.githubusercontent.com/2007088/112699616-35751b00-8e5a-11eb-9bf8-cc09af4847a9.PNG | width=100) ![MiniWasher](https://user-images.githubusercontent.com/3220618/136715514-d1cb86ac-4278-4012-b7d5-25300a313fcf.png | width=100) ![DishWasher](https://user-images.githubusercontent.com/3220618/138618307-c7b6a9f0-073e-44df-a70a-8c0acbcb033b.png | width=100)`

Most of the forks of this project that are 14 commits behind display the images properly; other forks which are two commits behind have the same problem.

**Comment by phrz** [comment]
Fixed
