### ISSUE TITLE
Everything works except the font

### ISSUE THREAD

**Issue by FS1961** [phrz/lg-washer-dryer-card#19]
Not sure if it's just me, but I got everything to work except the "digital clock" style font. Any assistance would be appreciated.

<img width="363" alt="Screenshot 2022-11-09 at 11 41 51 AM" src="https://user-images.githubusercontent.com/98458806/200809473-8fe92f36-d8a4-43de-8148-3579f181260d.png">

type: vertical-stack
cards:
  - type: picture-elements
    elements:
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/sensing.png
        state_image:
          Detecting: local/community/lg-washer-card/lg-icons/sensing-on.png
        style:
          top: 33%
          left: 33%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/wash.png
        state_image:
          Washing: local/community/lg-washer-card/lg-icons/wash-on.png
        style:
          top: 33%
          left: 51%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/rinse.png
        state_image:
          Rinsing: local/community/lg-washer-card/lg-icons/rinse-on.png
        style:
          top: 33%
          left: 69%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/spin.png
        state_image:
          Spinning: local/community/lg-washer-card/lg-icons/spin-on.png
        style:
          top: 33%
          left: 87%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer
        image: local/community/lg-washer-card/lg-icons/wifi.png
        state_image:
          'on': local/community/lg-washer-card/lg-icons/wifi-on.png
        style:
          top: 73%
          left: 32%
          width: 10%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_door_lock
        image: local/community/lg-washer-card/lg-icons/lock.png
        state_image:
          'on': local/community/lg-washer-card/lg-icons/lock-on.png
        style:
          top: 73%
          left: 45%
          width: 10%
          image-rendering: crisp
      - type: state-label
        entity: sensor.front_load_washer_remaining_time
        style:
          color: '#8df427'
          font-family: 7segment
          font-size: 35px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
    image: local/community/lg-washer-card/hass-combo-card-bg.png
  - type: conditional
    conditions:
      - entity: sensor.front_load_washer_run_state
        state_not: '-'
    card:
      type: entities
      entities:
        - entity: sensor.front_load_washer
          type: attribute
          attribute: current_course
          name: Current Course
          icon: mdi:tune-vertical-variant
        - entity: sensor.front_load_washer
          type: attribute
          attribute: water_temp
          name: Water Temperature
          icon: mdi:coolant-temperature
        - entity: sensor.front_load_washer
          type: attribute
          attribute: spin_speed
          name: Spin Speed
          icon: mdi:rotate-right
      state_color: false

**Comment by xjon685** [comment]
Me too,  I had the font working on Rpi 4,  but just migrated my install to Odroid Xu4,  the /config/www/7segment.css   was copied on the odroid.  The contents identical, but the font same as your example.
