### ISSUE TITLE
State_Image not showing, if dryer/washer is configured in a language different from english.

### ISSUE THREAD

**Issue by AndersWJ** [phrz/lg-washer-dryer-card#2]
I found, that the dryer .yaml and washer .yaml template files, had to be changed for the state images to work. Might be a good thing to add to the description or maybe solve this in a different way.

In my local language (Danish) - Some state values, are in the local language, if the washer and/or dryer is setup in that language.

**For the dryer, i changed the state values in the yaml from:**
Drying -> Tørrer
Cooling -> Køler

**For the washer i changed:**
Washing -> Vasker
Rinsing -> Skyller
Spinning -> Centrifugerer

I could not find an event for "Sensing" for my washer. It does have this feature, but the log never showed a value for this.

**Comment by phrz** [comment]
Thanks for sharing this. Clearly it would be impractical if not impossible to hardcode the terms used in every language. Unfortunately, it appears that the `sensor.washer` and `sensor.dryer` entities exposed by the LG integration only shows the current state in text form, there is no numerical enumeration that works across languages. So there appears to be no alternative to having to adjust your configuration for your language. I cannot speak to the lack of a "Sensing" state in Danish. If you find out that I'm wrong, that there is some sort of cross-language way to detect state, let me know, and I'd be happy to reassess this.

**Comment by phrz** [comment]
I think the textual states depend on either your LG App region, or your LG account's language setting. Can you confirm if you are able to adjust this to get English messages from your washer/dryer?

I am not suggesting that as a permanent fix, I only want to see if it can be changed in your region specifically. That way I can put two options in the README: change the config, or change your language.

**Comment by phrz** [comment]
Closing this issue as stale due to no response

**Comment by Tundersepa** [comment]
Hello! 

How or where did you change the language? I have the same story.

thanks in advance

Andres

**Comment by Tundersepa** [comment]
I fixed it, now it works :)
