### ISSUE TITLE
Format time from 0:00:00 to -:–:– for washer when complete and system is off

### ISSUE THREAD

**Issue by FS1961** [phrz/lg-washer-dryer-card#24]
When the unit is no longer washing and the status is off, the remaining time should reset to -:--:-- indicating that it's completely done? Would be different than no time remaining, it's done.

<img width="339" alt="Screenshot 2023-02-09 at 6 27 45 AM" src="https://user-images.githubusercontent.com/98458806/217732889-b7282614-287d-47a0-b1e5-c5149329141a.png">

**Comment by phrz** [comment]
See my answer [here](https://github.com/phrz/lg-washer-dryer-card/issues/22#issuecomment-1433485761), this depends on your own machine and how the LG integration shows its finished state, you have to edit your configuration accordingly.
