### ISSUE TITLE
[BUG] Repository structure for main is not compliant

### ISSUE THREAD

**Issue by thidkyar** [phrz/lg-washer-dryer-card#33]
Hi,

Thanks for the amazing work, however, looks like I'm not able to add this repository to HACS. Please see screenshot:

<img width="629" alt="image" src="https://github.com/phrz/lg-washer-dryer-card/assets/37986268/99bd5825-7fb9-4a30-bd54-72f5292fda98">

Thanks!

**Comment by phrz** [comment]
Hi, this is not a HACS plugin and requires manual installation; when I made this, I found HACS documentation lacking. I welcome contributions related to making this work in HACS. For now, you have to follow the instructions in the README.
