### ISSUE TITLE
[BUG] Respository structure format is not compliant for HACS

### ISSUE THREAD

**Issue by TheCre8r** [phrz/lg-washer-dryer-card#37]
**Describe the bug**
Attempted to add with HACS and it fails

**Screenshots**
![Screenshot_20241015_230922_Home Assistant.png](https://github.com/user-attachments/assets/d0ddee87-5139-4093-8ea2-e653c5fe0d8a)

**Comment by phrz** [comment]
Hi TheCre8r, this is not advertised as working with HACS. I found HACS documentation lacking when I originally made this project. If you want to make a pull request implementing HACS compatibility, I welcome it.
