### ISSUE TITLE
HACs compatible 

### ISSUE THREAD

**Issue by southwestflavorz** [phrz/lg-washer-dryer-card#5]
Any way to make this HACs compatible?

**Comment by phrz** [comment]
Hello, these cards consist of custom sensors implemented in `configuration.yaml`, custom assets served by HA, and custom cards __made out of existing card types__. The documentation for HACS is very limited, and I found no example for how to implement this particular type of card in HACS. I have mentioned elsewhere that as soon as it became apparent how to do this, I would. For the time being, HACS is out of scope and this is a "DIY install" card.
