### ISSUE TITLE
Unable to get images to display properly

### ISSUE THREAD

**Issue by amathews84** [phrz/lg-washer-dryer-card#6]
I’ve gotten the the washer and dryer cards added. However, the images don't appear correctly:

![image](https://user-images.githubusercontent.com/33185757/134965109-253d50da-6078-4e3e-a5a4-c6e03070ced2.png)

The images are saved in this directory per the instructions:
![image](https://user-images.githubusercontent.com/33185757/134965251-d28515c8-0bf3-4da3-83ef-401303cab3b5.png)

What's interesting is that the dryer image shows but all others do not.  I went back into washer-card.yaml and dryer-card.yaml to made sure all images reference the same directory path.

**Comment by phrz** [comment]
I would recommend you look at your web inspector Network tab (or similarly named), filtering to Image resources only, to determine (1) is your browser attempting to load the images at all? (2) if so, what URL is it trying to load for those images? (3) is it getting a 404, or is there some other issue?

Separately, try to type in the full URL of the image to see if it will load in a new tab of your browser.

Unfortunately, I do not know enough about the nuances of your Home Assistant server setup to offer specific guidance without much more information.
