### ISSUE TITLE
Add this repository to HACS

### ISSUE THREAD

**Issue by sebastiankliem** [phrz/lg-washer-dryer-card#9]
You've done great work on this cards, I really like these Lovelace cards! Have you considered to add your repo to [HACS](https://hacs.xyz) or adjust the folder structure, so one can [install it manually](https://hacs.xyz/docs/faq/custom_repositories) using HACS? I guess this would make it accessible for many more people.

**Comment by phrz** [comment]
Hi Sebastian and thank you! Please see my response here on this topic: https://github.com/phrz/lg-washer-dryer-card/issues/5#issuecomment-938713509

Until there is HACS documentation for cards built in YAML using other card components, I cannot do this. The documentation is very sparse.
